# Generated by Django 6.0.3 on 2026-04-04 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20, verbose_name='Nickname')),
                ('email', models.CharField(max_length=30, verbose_name='email')),
                ('password', models.CharField(max_length=16, verbose_name='password')),
            ],
        ),
    ]
